name: tests
on:
  push:

concurrency: 
  cancel-in-progress: true
  group: paddle-test-kit

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]

    steps:
    - name: Git checkout
      uses: actions/checkout@v5.0.0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    # https://github.com/ungoogled-software/ungoogled-chromium/issues/2804#issuecomment-2081611387
    # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md#option-1_the-easiest-way
    - name: Allow puppeteer sandbox
      run: |
        echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

    - name: Test 
      run: ./test.sh
      env: 
        VENDOR_ID: ${{ secrets.VENDOR_ID }}
        AUTH_CODE: ${{ secrets.AUTH_CODE }}