name: tests
on:
  push:
    
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v4.2.2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - name: Test 
      run: ./test.sh
      env: 
        VENDOR_ID: ${{ secrets.VENDOR_ID }}
        AUTH_CODE: ${{ secrets.AUTH_CODE }}